# Generated by Django 5.2.1 on 2025-06-04 09:47

import django.db.models.deletion
import phonenumber_field.modelfields
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='party_logos/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='PollingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PRESIDENT', 'President'), ('GOVERNOR', 'Governor'), ('SENATOR', 'Senator'), ('WOMEN_REP', 'Women Representative'), ('MP', 'Member of Parliament'), ('MCA', 'Member of County Assembly')], max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.county')),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.pollingcenter')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE')),
                ('is_verified', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('constituency', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='county', chained_model_field='county', on_delete=django.db.models.deletion.CASCADE, to='voting.constituency')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.county')),
                ('polling_center', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ward', chained_model_field='ward', on_delete=django.db.models.deletion.CASCADE, to='voting.pollingcenter')),
                ('polling_station', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='polling_center', chained_model_field='center', on_delete=django.db.models.deletion.CASCADE, to='voting.pollingstation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ward', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='constituency', chained_model_field='constituency', on_delete=django.db.models.deletion.CASCADE, to='voting.ward')),
            ],
        ),
        migrations.AddField(
            model_name='pollingcenter',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.ward'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='candidate_photos/')),
                ('constituency', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='county', chained_model_field='county', null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.constituency')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.county')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.party')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.position')),
                ('ward', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='constituency', chained_model_field='constituency', null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.position')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voter')),
            ],
            options={
                'unique_together': {('voter', 'position')},
            },
        ),
    ]
