# Generated by Django 4.2.11 on 2026-04-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_pollingcenter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingcenter',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
