# Generated by Django 4.2.11 on 2026-04-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_pollingcenter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='avg_voters_per_center',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ward',
            name='avg_voters_per_station',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ward',
            name='polling_centers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ward',
            name='polling_stations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ward',
            name='registered_voters_2022',
            field=models.IntegerField(default=0),
        ),
    ]
