# Generated by Django 4.2.11 on 2026-04-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_ward_avg_voters_per_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingcenter',
            name='registered_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='registered_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_stations', to='voting.pollingcenter'),
        ),
    ]
