from django.core.management.base import BaseCommand
from voting.models import Constituency, County

class Command(BaseCommand):
    help = 'Populate missing IEBC constituencies to reach 290'

    def handle(self, *args, **options):
        self.stdout.write('=== POPULATING MISSING IEBC CONSTITUENCIES ===')
        
        # Official IEBC constituencies (290 total)
        official_constituencies = [
            ('001', 'CHANGAMWE', '001', 'MOMBASA'),
            ('002', 'JOMVU', '001', 'MOMBASA'),
            ('003', 'KISAUNI', '001', 'MOMBASA'),
            ('004', 'NYALI', '001', 'MOMBASA'),
            ('005', 'LIKONI', '001', 'MOMBASA'),
            ('006', 'MVITA', '001', 'MOMBASA'),
            ('007', 'MSAMBWENI', '002', 'KWALE'),
            ('008', 'LUNGALUNGA', '002', 'KWALE'),
            ('009', 'MATUGA', '002', 'KWALE'),
            ('010', 'KINANGO', '002', 'KWALE'),
            ('011', 'KILIFI NORTH', '003', 'KILIFI'),
            ('012', 'KILIFI SOUTH', '003', 'KILIFI'),
            ('013', 'KALOLENI', '003', 'KILIFI'),
            ('014', 'RABAI', '003', 'KILIFI'),
            ('015', 'GANZE', '003', 'KILIFI'),
            ('016', 'MALINDI', '003', 'KILIFI'),
            ('017', 'MAGARINI', '003', 'KILIFI'),
            ('018', 'GARSEN', '004', 'TANA RIVER'),
            ('019', 'GALOLE', '004', 'TANA RIVER'),
            ('020', 'BURA', '004', 'TANA RIVER'),
            ('021', 'LAMU EAST', '005', 'LAMU'),
            ('022', 'LAMU WEST', '005', 'LAMU'),
            ('023', 'TAVETA', '006', 'TAITA TAVETA'),
            ('024', 'WUNDANYI', '006', 'TAITA TAVETA'),
            ('025', 'MWATATE', '006', 'TAITA TAVETA'),
            ('026', 'VOI', '006', 'TAITA TAVETA'),
            ('027', 'GARISSA TOWNSHIP', '007', 'GARISSA'),
            ('028', 'BALAMBALA', '007', 'GARISSA'),
            ('029', 'LAGDERA', '007', 'GARISSA'),
            ('030', 'DADAAB', '007', 'GARISSA'),
            ('031', 'FAFI', '007', 'GARISSA'),
            ('032', 'IJARA', '007', 'GARISSA'),
            ('033', 'WAJIR NORTH', '008', 'WAJIR'),
            ('034', 'WAJIR EAST', '008', 'WAJIR'),
            ('035', 'TARBAJ', '008', 'WAJIR'),
            ('036', 'WAJIR WEST', '008', 'WAJIR'),
            ('037', 'ELDAS', '008', 'WAJIR'),
            ('038', 'WAJIR SOUTH', '008', 'WAJIR'),
            ('039', 'MANDERA WEST', '009', 'MANDERA'),
            ('040', 'BANISSA', '009', 'MANDERA'),
            ('041', 'MANDERA NORTH', '009', 'MANDERA'),
            ('042', 'MANDERA SOUTH', '009', 'MANDERA'),
            ('043', 'MANDERA EAST', '009', 'MANDERA'),
            ('044', 'LAFEY', '009', 'MANDERA'),
            ('045', 'MOYALE', '010', 'MARSABIT'),
            ('046', 'NORTH HORR', '010', 'MARSABIT'),
            ('047', 'SAKU', '010', 'MARSABIT'),
            ('048', 'LAISAMIS', '010', 'MARSABIT'),
            ('049', 'ISIOLO NORTH', '011', 'ISIOLO'),
            ('050', 'ISIOLO SOUTH', '011', 'ISIOLO'),
            ('051', 'IGEMBE SOUTH', '012', 'MERU'),
            ('052', 'IGEMBE CENTRAL', '012', 'MERU'),
            ('053', 'IGEMBE NORTH', '012', 'MERU'),
            ('054', 'TIGANIA WEST', '012', 'MERU'),
            ('055', 'TIGANIA EAST', '012', 'MERU'),
            ('056', 'NORTH IMENTI', '012', 'MERU'),
            ('057', 'BUURI', '012', 'MERU'),
            ('058', 'CENTRAL IMENTI', '012', 'MERU'),
            ('059', 'SOUTH IMENTI', '012', 'MERU'),
            ('060', 'MAARA', '013', 'THARAKA - NITHI'),
            ('061', 'CHUKA/IGAMBANG\'OMBE', '013', 'THARAKA - NITHI'),
            ('062', 'THARAKA', '013', 'THARAKA - NITHI'),
            ('063', 'MANYATTA', '014', 'EMBU'),
            ('064', 'RUNYENJES', '014', 'EMBU'),
            ('065', 'MBEERE SOUTH', '014', 'EMBU'),
            ('066', 'MBEERE NORTH', '014', 'EMBU'),
            ('067', 'MWINGI NORTH', '015', 'KITUI'),
            ('068', 'MWINGI WEST', '015', 'KITUI'),
            ('069', 'MWINGI CENTRAL', '015', 'KITUI'),
            ('070', 'KITUI WEST', '015', 'KITUI'),
            ('071', 'KITUI RURAL', '015', 'KITUI'),
            ('072', 'KITUI CENTRAL', '015', 'KITUI'),
            ('073', 'KITUI EAST', '015', 'KITUI'),
            ('074', 'KITUI SOUTH', '015', 'KITUI'),
            ('075', 'MASINGA', '016', 'MACHAKOS'),
            ('076', 'YATTA', '016', 'MACHAKOS'),
            ('077', 'KANGUNDO', '016', 'MACHAKOS'),
            ('078', 'MATUNGULU', '016', 'MACHAKOS'),
            ('079', 'KATHIANI', '016', 'MACHAKOS'),
            ('080', 'MAVOKO', '016', 'MACHAKOS'),
            ('081', 'MACHAKOS TOWN', '016', 'MACHAKOS'),
            ('082', 'MWALA', '016', 'MACHAKOS'),
            ('083', 'MBOONI', '017', 'MAKUENI'),
            ('084', 'KILOME', '017', 'MAKUENI'),
            ('085', 'KAITI', '017', 'MAKUENI'),
            ('086', 'MAKUENI', '017', 'MAKUENI'),
            ('087', 'KIBWEZI WEST', '017', 'MAKUENI'),
            ('088', 'KIBWEZI EAST', '017', 'MAKUENI'),
            ('089', 'KINANGOP', '018', 'NYANDARUA'),
            ('090', 'KIPIPIRI', '018', 'NYANDARUA'),
            ('091', 'OL KALOU', '018', 'NYANDARUA'),
            ('092', 'OL JOROK', '018', 'NYANDARUA'),
            ('093', 'NDARAGWA', '018', 'NYANDARUA'),
            ('094', 'TETU', '019', 'NYERI'),
            ('095', 'KIENI', '019', 'NYERI'),
            ('096', 'MATHIRA', '019', 'NYERI'),
            ('097', 'OTHAYA', '019', 'NYERI'),
            ('098', 'MUKURWEINI', '019', 'NYERI'),
            ('099', 'NYERI TOWN', '019', 'NYERI'),
            ('100', 'MWEA', '020', 'KIRINYAGA'),
            ('101', 'GICHUGU', '020', 'KIRINYAGA'),
            ('102', 'NDIA', '020', 'KIRINYAGA'),
            ('103', 'KIRINYAGA CENTRAL', '020', 'KIRINYAGA'),
            ('104', 'KANGEMA', '021', 'MURANG\'A'),
            ('105', 'MATHIOYA', '021', 'MURANG\'A'),
            ('106', 'KIHARU', '021', 'MURANG\'A'),
            ('107', 'KIGUMO', '021', 'MURANG\'A'),
            ('108', 'MARAGWA', '021', 'MURANG\'A'),
            ('109', 'KANDARA', '021', 'MURANG\'A'),
            ('110', 'GATANGA', '021', 'MURANG\'A'),
            ('111', 'GATUNDU SOUTH', '022', 'KIAMBU'),
            ('112', 'GATUNDU NORTH', '022', 'KIAMBU'),
            ('113', 'JUJA', '022', 'KIAMBU'),
            ('114', 'THIKA TOWN', '022', 'KIAMBU'),
            ('115', 'RUIRU', '022', 'KIAMBU'),
            ('116', 'GITHUNGURI', '022', 'KIAMBU'),
            ('117', 'KIAMBU', '022', 'KIAMBU'),
            ('118', 'KIAMBAA', '022', 'KIAMBU'),
            ('119', 'KABETE', '022', 'KIAMBU'),
            ('120', 'KIKUYU', '022', 'KIAMBU'),
            ('121', 'LIMURU', '022', 'KIAMBU'),
            ('122', 'LARI', '022', 'KIAMBU'),
            ('123', 'TURKANA NORTH', '023', 'TURKANA'),
            ('124', 'TURKANA WEST', '023', 'TURKANA'),
            ('125', 'TURKANA CENTRAL', '023', 'TURKANA'),
            ('126', 'LOIMA', '023', 'TURKANA'),
            ('127', 'TURKANA SOUTH', '023', 'TURKANA'),
            ('128', 'TURKANA EAST', '023', 'TURKANA'),
            ('129', 'KAPENGURIA', '024', 'WEST POKOT'),
            ('130', 'SIGOR', '024', 'WEST POKOT'),
            ('131', 'KACHELIBA', '024', 'WEST POKOT'),
            ('132', 'POKOT SOUTH', '024', 'WEST POKOT'),
            ('133', 'SAMBURU WEST', '025', 'SAMBURU'),
            ('134', 'SAMBURU NORTH', '025', 'SAMBURU'),
            ('135', 'SAMBURU EAST', '025', 'SAMBURU'),
            ('136', 'KWANZA', '026', 'TRANS NZOIA'),
            ('137', 'ENDEBESS', '026', 'TRANS NZOIA'),
            ('138', 'SABOTI', '026', 'TRANS NZOIA'),
            ('139', 'KIMININI', '026', 'TRANS NZOIA'),
            ('140', 'CHERANGANY', '026', 'TRANS NZOIA'),
            ('141', 'SOY', '027', 'UASIN GISHU'),
            ('142', 'TURBO', '027', 'UASIN GISHU'),
            ('143', 'MOIBEN', '027', 'UASIN GISHU'),
            ('144', 'AINABKOI', '027', 'UASIN GISHU'),
            ('145', 'KAPSERET', '027', 'UASIN GISHU'),
            ('146', 'KESSES', '027', 'UASIN GISHU'),
            ('147', 'MARAKWET EAST', '028', 'ELGEYO/MARAKWET'),
            ('148', 'MARAKWET WEST', '028', 'ELGEYO/MARAKWET'),
            ('149', 'KEIYO NORTH', '028', 'ELGEYO/MARAKWET'),
            ('150', 'KEIYO SOUTH', '028', 'ELGEYO/MARAKWET'),
            ('151', 'TINDERET', '029', 'NANDI'),
            ('152', 'ALDAI', '029', 'NANDI'),
            ('153', 'NANDI HILLS', '029', 'NANDI'),
            ('154', 'CHESUMEI', '029', 'NANDI'),
            ('155', 'EMGWEN', '029', 'NANDI'),
            ('156', 'MOSOP', '029', 'NANDI'),
            ('157', 'TIATY', '030', 'BARINGO'),
            ('158', 'BARINGO NORTH', '030', 'BARINGO'),
            ('159', 'BARINGO CENTRAL', '030', 'BARINGO'),
            ('160', 'BARINGO SOUTH', '030', 'BARINGO'),
            ('161', 'MOGOTIO', '030', 'BARINGO'),
            ('162', 'ELDAMA RAVINE', '030', 'BARINGO'),
            ('163', 'LAIKIPIA WEST', '031', 'LAIKIPIA'),
            ('164', 'LAIKIPIA EAST', '031', 'LAIKIPIA'),
            ('165', 'LAIKIPIA NORTH', '031', 'LAIKIPIA'),
            ('166', 'MOLO', '032', 'NAKURU'),
            ('167', 'NJORO', '032', 'NAKURU'),
            ('168', 'NAIVASHA', '032', 'NAKURU'),
            ('169', 'GILGIL', '032', 'NAKURU'),
            ('170', 'KURESOI SOUTH', '032', 'NAKURU'),
            ('171', 'KURESOI NORTH', '032', 'NAKURU'),
            ('172', 'SUBUKIA', '032', 'NAKURU'),
            ('173', 'RONGAI', '032', 'NAKURU'),
            ('174', 'BAHATI', '032', 'NAKURU'),
            ('175', 'NAKURU TOWN WEST', '032', 'NAKURU'),
            ('176', 'NAKURU TOWN EAST', '032', 'NAKURU'),
            ('177', 'KILGORIS', '033', 'NAROK'),
            ('178', 'EMURUA DIKIRR', '033', 'NAROK'),
            ('179', 'NAROK NORTH', '033', 'NAROK'),
            ('180', 'NAROK EAST', '033', 'NAROK'),
            ('181', 'NAROK SOUTH', '033', 'NAROK'),
            ('182', 'NAROK WEST', '033', 'NAROK'),
            ('183', 'KAJIADO NORTH', '034', 'KAJIADO'),
            ('184', 'KAJIADO CENTRAL', '034', 'KAJIADO'),
            ('185', 'KAJIADO EAST', '034', 'KAJIADO'),
            ('186', 'KAJIADO WEST', '034', 'KAJIADO'),
            ('187', 'KAJIADO SOUTH', '034', 'KAJIADO'),
            ('188', 'KIPKELION EAST', '035', 'KERICHO'),
            ('189', 'KIPKELION WEST', '035', 'KERICHO'),
            ('190', 'AINAMOI', '035', 'KERICHO'),
            ('191', 'BURETI', '035', 'KERICHO'),
            ('192', 'BELGUT', '035', 'KERICHO'),
            ('193', 'SIGOWET/SOIN', '035', 'KERICHO'),
            ('194', 'SOTIK', '036', 'BOMET'),
            ('195', 'CHEPALUNGU', '036', 'BOMET'),
            ('196', 'BOMET EAST', '036', 'BOMET'),
            ('197', 'BOMET CENTRAL', '036', 'BOMET'),
            ('198', 'KONOIN', '036', 'BOMET'),
            ('199', 'LUGARI', '037', 'KAKAMEGA'),
            ('200', 'LIKUYANI', '037', 'KAKAMEGA'),
            ('201', 'MALAVA', '037', 'KAKAMEGA'),
            ('202', 'LURAMBI', '037', 'KAKAMEGA'),
            ('203', 'NAVAKHOLO', '037', 'KAKAMEGA'),
            ('204', 'MUMIAS WEST', '037', 'KAKAMEGA'),
            ('205', 'MUMIAS EAST', '037', 'KAKAMEGA'),
            ('206', 'MATUNGU', '037', 'KAKAMEGA'),
            ('207', 'BUTERE', '037', 'KAKAMEGA'),
            ('208', 'KHWISERO', '037', 'KAKAMEGA'),
            ('209', 'SHINYALU', '037', 'KAKAMEGA'),
            ('210', 'IKOLOMANI', '037', 'KAKAMEGA'),
            ('211', 'VIHIGA', '038', 'VIHIGA'),
            ('212', 'SABATIA', '038', 'VIHIGA'),
            ('213', 'HAMISI', '038', 'VIHIGA'),
            ('214', 'LUANDA', '038', 'VIHIGA'),
            ('215', 'EMUHAYA', '038', 'VIHIGA'),
            ('216', 'MT. ELGON', '039', 'BUNGOMA'),
            ('217', 'SIRISIA', '039', 'BUNGOMA'),
            ('218', 'KABUCHAI', '039', 'BUNGOMA'),
            ('219', 'BUMULA', '039', 'BUNGOMA'),
            ('220', 'KANDUYI', '039', 'BUNGOMA'),
            ('221', 'WEBUYE EAST', '039', 'BUNGOMA'),
            ('222', 'WEBUYE WEST', '039', 'BUNGOMA'),
            ('223', 'KIMILILI', '039', 'BUNGOMA'),
            ('224', 'TONGAREN', '039', 'BUNGOMA'),
            ('225', 'TESO NORTH', '040', 'BUSIA'),
            ('226', 'TESO SOUTH', '040', 'BUSIA'),
            ('227', 'NAMBALE', '040', 'BUSIA'),
            ('228', 'MATAYOS', '040', 'BUSIA'),
            ('229', 'BUTULA', '040', 'BUSIA'),
            ('230', 'FUNYULA', '040', 'BUSIA'),
            ('231', 'BUDALANGI', '040', 'BUSIA'),
            ('232', 'UGENYA', '041', 'SIAYA'),
            ('233', 'UGUNJA', '041', 'SIAYA'),
            ('234', 'ALEGO USONGA', '041', 'SIAYA'),
            ('235', 'GEM', '041', 'SIAYA'),
            ('236', 'BONDO', '041', 'SIAYA'),
            ('237', 'RARIEDA', '041', 'SIAYA'),
            ('238', 'KISUMU EAST', '042', 'KISUMU'),
            ('239', 'KISUMU WEST', '042', 'KISUMU'),
            ('240', 'KISUMU CENTRAL', '042', 'KISUMU'),
            ('241', 'SEME', '042', 'KISUMU'),
            ('242', 'NYANDO', '042', 'KISUMU'),
            ('243', 'MUHORONI', '042', 'KISUMU'),
            ('244', 'NYAKACH', '042', 'KISUMU'),
            ('245', 'KASIPUL', '043', 'HOMA BAY'),
            ('246', 'KABONDO KASIPUL', '043', 'HOMA BAY'),
            ('247', 'KARACHUONYO', '043', 'HOMA BAY'),
            ('248', 'RANGWE', '043', 'HOMA BAY'),
            ('249', 'HOMA BAY TOWN', '043', 'HOMA BAY'),
            ('250', 'NDHIWA', '043', 'HOMA BAY'),
            ('251', 'SUBA NORTH', '043', 'HOMA BAY'),
            ('252', 'SUBA SOUTH', '043', 'HOMA BAY'),
            ('253', 'RONGO', '044', 'MIGORI'),
            ('254', 'AWENDO', '044', 'MIGORI'),
            ('255', 'SUNA EAST', '044', 'MIGORI'),
            ('256', 'SUNA WEST', '044', 'MIGORI'),
            ('257', 'URIRI', '044', 'MIGORI'),
            ('258', 'NYATIKE', '044', 'MIGORI'),
            ('259', 'KURIA WEST', '044', 'MIGORI'),
            ('260', 'KURIA EAST', '044', 'MIGORI'),
            ('261', 'BONCHARI', '045', 'KISII'),
            ('262', 'SOUTH MUGIRANGO', '045', 'KISII'),
            ('263', 'BOMACHOGE BORABU', '045', 'KISII'),
            ('264', 'BOBASI', '045', 'KISII'),
            ('265', 'BOMACHOGE CHACHE', '045', 'KISII'),
            ('266', 'NYARIBARI MASABA', '045', 'KISII'),
            ('267', 'NYARIBARI CHACHE', '045', 'KISII'),
            ('268', 'KITUTU CHACHE NORTH', '045', 'KISII'),
            ('269', 'KITUTU CHACHE SOUTH', '045', 'KISII'),
            ('270', 'KITUTU MASABA', '046', 'NYAMIRA'),
            ('271', 'WEST MUGIRANGO', '046', 'NYAMIRA'),
            ('272', 'NORTH MUGIRANGO', '046', 'NYAMIRA'),
            ('273', 'BORABU', '046', 'NYAMIRA'),
            ('274', 'WESTLANDS', '047', 'NAIROBI CITY'),
            ('275', 'DAGORETTI NORTH', '047', 'NAIROBI CITY'),
            ('276', 'DAGORETTI SOUTH', '047', 'NAIROBI CITY'),
            ('277', 'LANGATA', '047', 'NAIROBI CITY'),
            ('278', 'KIBRA', '047', 'NAIROBI CITY'),
            ('279', 'ROYSAMBU', '047', 'NAIROBI CITY'),
            ('280', 'KASARANI', '047', 'NAIROBI CITY'),
            ('281', 'RUARAKA', '047', 'NAIROBI CITY'),
            ('282', 'EMBAKASI SOUTH', '047', 'NAIROBI CITY'),
            ('283', 'EMBAKASI NORTH', '047', 'NAIROBI CITY'),
            ('284', 'EMBAKASI CENTRAL', '047', 'NAIROBI CITY'),
            ('285', 'EMBAKASI EAST', '047', 'NAIROBI CITY'),
            ('286', 'EMBAKASI WEST', '047', 'NAIROBI CITY'),
            ('287', 'MAKADARA', '047', 'NAIROBI CITY'),
            ('288', 'KAMUKUNJI', '047', 'NAIROBI CITY'),
            ('289', 'STAREHE', '047', 'NAIROBI CITY'),
            ('290', 'MATHARE', '047', 'NAIROBI CITY')
        ]
        
        self.stdout.write(f'Official IEBC constituencies: {len(official_constituencies)}')
        self.stdout.write(f'Current constituencies in database: {Constituency.objects.count()}')
        
        # Get existing constituency codes
        existing_codes = set(Constituency.objects.values_list('code', flat=True))
        
        # Find missing constituencies
        missing_constituencies = []
        for code, name, county_code, county_name in official_constituencies:
            if code not in existing_codes:
                missing_constituencies.append((code, name, county_code, county_name))
        
        self.stdout.write(f'Missing constituencies: {len(missing_constituencies)}')
        
        # Add missing constituencies
        added_count = 0
        for code, name, county_code, county_name in missing_constituencies:
            try:
                # Get or create the county
                county, _ = County.objects.get_or_create(
                    code=county_code,
                    defaults={'name': county_name}
                )
                
                # Create the constituency
                Constituency.objects.get_or_create(
                    code=code,
                    county=county,
                    defaults={'name': name}
                )
                
                added_count += 1
                self.stdout.write(f'Added: {code} - {name} ({county_name})')
                
            except Exception as e:
                self.stdout.write(self.style.ERROR(f'Error adding {code} - {name}: {e}'))
        
        self.stdout.write(f'\n=== FINAL RESULTS ===')
        self.stdout.write(f'Added {added_count} missing constituencies')
        self.stdout.write(f'Total constituencies now: {Constituency.objects.count()}')
        
        if Constituency.objects.count() == 290:
            self.stdout.write(self.style.SUCCESS('✅ PERFECT! Kenya now has official 290 constituencies'))
        else:
            self.stdout.write(f'⚠️  Current: {Constituency.objects.count()}, Target: 290')
